
package edu.up.bsi.soap.progserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProgressaoCalcService", targetNamespace = "http://progserver.soap.bsi.up.edu/", wsdlLocation = "http://localhost:8080/ProgressaoCalc?wsdl")
public class ProgressaoCalcService
    extends Service
{

    private final static URL PROGRESSAOCALCSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROGRESSAOCALCSERVICE_EXCEPTION;
    private final static QName PROGRESSAOCALCSERVICE_QNAME = new QName("http://progserver.soap.bsi.up.edu/", "ProgressaoCalcService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ProgressaoCalc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROGRESSAOCALCSERVICE_WSDL_LOCATION = url;
        PROGRESSAOCALCSERVICE_EXCEPTION = e;
    }

    public ProgressaoCalcService() {
        super(__getWsdlLocation(), PROGRESSAOCALCSERVICE_QNAME);
    }

    public ProgressaoCalcService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROGRESSAOCALCSERVICE_QNAME, features);
    }

    public ProgressaoCalcService(URL wsdlLocation) {
        super(wsdlLocation, PROGRESSAOCALCSERVICE_QNAME);
    }

    public ProgressaoCalcService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROGRESSAOCALCSERVICE_QNAME, features);
    }

    public ProgressaoCalcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProgressaoCalcService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProgressaoCalc
     */
    @WebEndpoint(name = "ProgressaoCalcPort")
    public ProgressaoCalc getProgressaoCalcPort() {
        return super.getPort(new QName("http://progserver.soap.bsi.up.edu/", "ProgressaoCalcPort"), ProgressaoCalc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProgressaoCalc
     */
    @WebEndpoint(name = "ProgressaoCalcPort")
    public ProgressaoCalc getProgressaoCalcPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://progserver.soap.bsi.up.edu/", "ProgressaoCalcPort"), ProgressaoCalc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROGRESSAOCALCSERVICE_EXCEPTION!= null) {
            throw PROGRESSAOCALCSERVICE_EXCEPTION;
        }
        return PROGRESSAOCALCSERVICE_WSDL_LOCATION;
    }

}
